#include <cpp11.hpp>
#include <cpp11/declarations.hpp>
#include <boost/math/distributions.hpp>
#include "boostmath/macros.hpp"

BINARY_DISTRIBUTION_BOOST_NEW(arcsine, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(beta, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(binomial, int, double)
BINARY_DISTRIBUTION_BOOST_NEW(cauchy, double, double)
UNARY_DISTRIBUTION_BOOST_NEW(chi_squared, double)
UNARY_DISTRIBUTION_BOOST_NEW(exponential, double)
BINARY_DISTRIBUTION_BOOST_NEW(extreme_value, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(fisher_f, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(gamma, double, double)
UNARY_DISTRIBUTION_BOOST_NEW(geometric, double)
BINARY_DISTRIBUTION_BOOST_NEW(holtsmark, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(hyperexponential, std::vector<double>, std::vector<double>)
TERNARY_DISTRIBUTION_BOOST_NEW(hypergeometric, uint64_t, uint64_t, uint64_t)
BINARY_DISTRIBUTION_BOOST_NEW(inverse_chi_squared, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(inverse_gamma, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(inverse_gaussian, double, double)
UNARY_DISTRIBUTION_BOOST_NEW(kolmogorov_smirnov, int)
BINARY_DISTRIBUTION_BOOST_NEW(landau, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(laplace, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(logistic, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(lognormal, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(mapairy, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(negative_binomial, double, double)
TERNARY_DISTRIBUTION_BOOST_NEW(non_central_beta, double, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(non_central_chi_squared, double, double)
TERNARY_DISTRIBUTION_BOOST_NEW(non_central_f, double, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(non_central_t, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(normal, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(pareto, double, double)
UNARY_DISTRIBUTION_BOOST_NEW(poisson, double)
UNARY_DISTRIBUTION_BOOST_NEW(rayleigh, double)
BINARY_DISTRIBUTION_BOOST_NEW(saspoint5, double, double)
TERNARY_DISTRIBUTION_BOOST_NEW(skew_normal, double, double, double)
UNARY_DISTRIBUTION_BOOST_NEW(students_t, double)
TERNARY_DISTRIBUTION_BOOST_NEW(triangular, double, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(uniform, double, double)
BINARY_DISTRIBUTION_BOOST_NEW(weibull, double, double)
